#ifndef RF_GLOBAL_H
#define RF_GLOBAL_H
#define SG_OPT_THREAD       0x00000001 
#define SG_OPT_OUTC_TYPE    0x00000002 
#define SG_OPT_SWTCH_TWO    0x00000004 
#define SG_OPT_SWTCH_THREE  0x00000008 
#define SG_OPT_SWTCH_FOUR   0x00000010 
#define SG_OPT_SWTCH_FIVE   0x00000020 
#define SG_OPT_SWTCH_SIX    0x00000040 
#define SG_OPT_SWTCH_SEVEN  0x00000080 
#define SG_OPT_REAL_TIME    0x00000100 
#define SG_CPU_TIME   0  
#define SG_BETA        1  
#define SG_LAMBDA_CT   2  
#define SG_LAMBDA      3  
#define SG_CONVG_CT    4  
#define SG_YHAT        5  
#define SG_LAMBDA_MIN  6  
#define SG_LAMBDA_1SE_MIN  7  
#define SG_LAMBDA_1SE_MAX  8  
#define SG_LAMBDA_ERR      9  
#define SG_LAMBDA_CVSD    10  
#define SG_MEMB_ID        1  
#define SG_BOOT_CT        2  
#define SG_ACLS_ID        3  
#define SG_OCLS_ID        4  
#define SG_ARGR_ID        5  
#define SG_ORGR_ID        6  
#define SG_ACDRGR_ID      7  
#define SG_OCDRGR_ID      8  
#define SG_ER_CLAS        9  
#define SG_ER_REGR       10  
#define SG_LEAF_CT       11  
#define SG_SEED_ID       12  
#define SG_EMP_RSK       13  
#define SG_OEMP_RSK      14  
#define SG_NODE_STAT     15  
#define SG_TREE_ID       16  
#define SG_NODE_ID       17  
#define SG_NODE_SZ       18  
#define SG_BR_NODE_ID    19  
#define SG_BETA_Z        20  
#define SG_BETA_P        21  
#define SG_YBAR          22  
#define SG_YSTAR         23  
#define SG_BSF_ORD       24  
#define SG_RMBR_TN_CT    25  
#define SG_OMBR_TN_CT    26  
#define SG_RMBR_TN_ID    27  
#define SG_OMBR_TN_ID    28  
#define SG_AMBR_TN_ID    29  
#define SG_PR_NODE_ID    30  
#define SG_OPT_LO_GROW   31  
#define SG_OPT_HI_GROW   32  
#define REGR_CDL    1
#define CLAS_CDL    2
#define REGR_CRT    3
#define CLAS_CRT    4
#define RAND_CRT    5
#define SG_SURV_TDC 6
#define ROOT 0x00
#define OUTC_CART   0x01
#define OUTC_LASSO  0x02
#define SG_EPSILON 1.0e-9
#define SG_THREADV_NFOLD 0
#define SG_THREADV_NTREE 1
#endif
